Repository androidvitb/Tailorwind, pull requests merged in 2025-01, with the labels that each got.

#8 Seamless Navigation with Scroll-to-Top Button on Homepage
  index.html
  main.css
  package-lock.json
Labels: acwoc, easy

#9 new: added grid-layout-generator feature
  grid-layout-generator.html
  main.css
  scripts/grid-layout-generator.js
  tools-and-generator.html
Labels: acwoc, hard

#11 new: added Table Generator page with features
  public/Homepage-HeroImage.png
  public/grid_layout_gen_image.png
  public/table_gen_image.png
  scripts/table-generator.js
  table-generator.html
  tools-and-generator.html
Labels: acwoc, hard

#14 updated css made responsive
  index.html
Labels: acwoc, medium

#17 new: Form generator page with functionality and some tweaks on homepage.
  form-generator.html
  index.html
  public/form-generator.png
  scripts/form-generator.js
  tools-and-generator.html
Labels: acwoc, hard

#19 Updated to Dynamic Copywrite
  index.html
  tools-and-generator.html
Labels: acwoc, easy

#21 🚀✨ Enhancing UI/UX: Interactive Button Effects Added!
  index.html
Labels: acwoc, easy

#23 🎨✨ Enhanced the UI/UX of the FAQ Section!
  index.html
Labels: acwoc, easy

#27 Enable of the Dark Mode Throughout the Website
  card-generator.html
  form-generator.html
  grid-layout-generator.html
  index.html
  main.css
  scripts/card-generator.js
  scripts/form-generator.js
  scripts/grid-layout-generator.js
  scripts/table-generator.js
  scripts/tools-and-generator.js
  table-generator.html
  tools-and-generator.html
Labels: acwoc, hard

#30 Bug Fix of Vercel & Vite Configuration and Redirection Issue
  index.html
  package-lock.json
  package.json
  tools-and-generator.html
  vercel.json
  vite.config.js
Labels: acwoc, hard

#31 navbar- generator
  .DS_Store
  index.html
  navbar.html
  public/.DS_Store
  public/navbar.png
  scripts/navbar-generator.js
Labels: acwoc, hard

#33 🎉 Enhanced Contact Page with Interactive Hover Effects! 🚀
  index.html
Labels: acwoc, easy

#37 Fix the Routing of Navbar Generator Page for Vercel
  vercel.json
  vite.config.js
Labels: acwoc, easy

#40 created the get started page as login page
  get-started.css
  get-started.html
  index.html
  login-bg.jpeg
Labels: acwoc, hard

#44 Enhanced the UI Components, Fixed the responsiveness bugs and added t…
  index.html
  navbar.html
  public/navbar.png
  tools-and-generator.html
Labels: acwoc, hard

#42 🖱️ Added Scroll Button to Tools & Generator Page
  tools-and-generator.html
Labels: acwoc, medium

#45 added smooth hovering effects and made UI of navbar more appealing
  index.html
  package-lock.json
Labels: acwoc, medium

#48 added the smooth hover effects of buttons in tools & generator page
  index.html
  tools-and-generator.html
Labels: acwoc, medium

#49 made the navbar sticky
  index.html
Labels: acwoc, easy
